### ISSUE TITLE
cannot GET 'file path' error still occuring

### ISSUE THREAD

**Issue by deltaarc** [imlolman/chatgpt-plugin-csv-excel-generator#2]
Hello,

I've tried on multiple occasions, waiting multiple days, and the links never work.
Having a text format of the spreadsheet issues by ChatGPT works, but the file download never does, even when asking to re-generate the links.

**Comment by imlolman** [comment]
Hey, The issue has been resolved.
The server has been changed from vercel to custom server to make it more stable.
